[clusters]
cluster1 ansible_host=x.x.x.x ansible_user=superuser ansible_password=password
; cluster2 ansible_host=x.x.x.x ansible_user=superuser ansible_password=password

[switches]
switch1 ansible_host=x.x.x.x ansible_user=admin ansible_password=password
; switch2 ansible_host=x.x.x.x ansible_user=admin ansible_password=password