# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ibm
name: storage_virtualize
version: 2.0.0
readme: README.md
authors:
  - Shilpi Jain (github.com/Shilpi-J)
description: Ansible Collections for IBM Storage Virtualize
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - storage
repository: https://github.com/ansible-collections/ibm.storage_virtualize
homepage: https://github.com/ansible-collections/ibm.storage_virtualize
issues: https://github.com/ansible-collections/ibm.storage_virtualize/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
