name: ibm.storage_virtualize Ansible galaxy importer CI
on:
  push:
  pull_request:
  schedule:
    - cron: '25 10 * * *'

jobs:
  galaxy-importer:
    name: Validate storage_virtualize with galaxy-importer tool.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade PIP
        run: python3.9 -m pip install --upgrade pip

      - name: Install ansible
        run: python3.9 -m pip install ansible --disable-pip-version-check

      - name: Install galaxy-importer tool
        run: python3.9 -m pip install galaxy_importer --disable-pip-version-check

      - name: Make directory to sync
        run: |
          pwd
          mkdir -p ansible_collections/ibm/storage_virtualize
          rsync -av . ansible_collections/ibm/storage_virtualize --exclude ansible_collections/ibm/storage_virtualize

      - name: Build the tar package
        run: ansible-galaxy collection build
        working-directory: ./ansible_collections/ibm/storage_virtualize

      - name: Run galaxy-importer tool on storage_virtualize
        run: |
          export GALAXY_IMPORTER_CONFIG=$(readlink -f galaxy-importer.cfg)
          env | grep galaxy
          python3.9 -m galaxy_importer.main ibm-storage_virtualize-*.tar.gz
        working-directory: ./ansible_collections/ibm/storage_virtualize
